export const SET_SORT_FILTER = "SET_SORT_FILTER";
export const SET_SIZE_FILTER = "SET_SIZE_FILTER";

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';